#pragma once

#include "../Generator/TensorField.h" // We'll move this to Data later or wrap it here
#include "Terrain.h"
#include <memory>

namespace Genesis::Data {

// The World Context holds all the data generated by the steps
struct World {
  // Step 1: Macro
  std::shared_ptr<Terrain> terrain;

  // Step 2: Infrastructure
  // Currently utilizing the existing class, but technically it's acting as Data
  // here
  std::shared_ptr<Genesis::Generator::TensorField> tensorField;

  World() {
    terrain = std::make_shared<Terrain>();
    tensorField = std::make_shared<Genesis::Generator::TensorField>(100, 100);
  }
};

} // namespace Genesis::Data
